### ISSUE TITLE
图片上传失败

### ISSUE THREAD

**Issue by inkss** [dishcheng/cosUploadV5#8]
```html
<pre><code><h1>Invalid handle provided</h1>Guzzle\Common\Exception\InvalidArgumentException: Invalid handle provided in /usr/plugins/cosUploadV5/src/Guzzle/Http/Curl/CurlHandle.php:237
Stack trace:
#0 /usr/plugins/cosUploadV5/src/Guzzle/Http/Curl/CurlHandle.php(223): Guzzle\Http\Curl\CurlHandle-&gt;__construct()
#1 /usr/plugins/cosUploadV5/src/Guzzle/Http/Curl/CurlMulti.php(194): Guzzle\Http\Curl\CurlHandle::factory()
#2 /usr/plugins/cosUploadV5/src/Guzzle/Http/Curl/CurlMulti.php(179): Guzzle\Http\Curl\CurlMulti-&gt;createCurlHandle()
#3 /usr/plugins/cosUploadV5/src/Guzzle/Http/Curl/CurlMulti.php(162): Guzzle\Http\Curl\CurlMulti-&gt;addHandle()
#4 /usr/plugins/cosUploadV5/src/Guzzle/Http/Curl/CurlMulti.php(71): Guzzle\Http\Curl\CurlMulti-&gt;beforeSend()
#5 /usr/plugins/cosUploadV5/src/Guzzle/Http/Curl/CurlMultiProxy.php(91): Guzzle\Http\Curl\CurlMulti-&gt;add()
#6 /usr/plugins/cosUploadV5/src/Guzzle/Http/Client.php(284): Guzzle\Http\Curl\CurlMultiProxy-&gt;send()
#7 /usr/plugins/cosUploadV5/src/Guzzle/Service/Client.php(136): Guzzle\Http\Client-&gt;send()
#8 /usr/plugins/cosUploadV5/src/Guzzle/Service/Command/AbstractCommand.php(153): Guzzle\Service\Client-&gt;execute()
#9 /usr/plugins/cosUploadV5/src/Guzzle/Service/Command/AbstractCommand.php(189): Guzzle\Service\Command\AbstractCommand-&gt;execute()
#10 /usr/plugins/cosUploadV5/src/Guzzle/Service/Client.php(76): Guzzle\Service\Command\AbstractCommand-&gt;getResult()
#11 /usr/plugins/cosUploadV5/src/Qcloud/Cos/Client.php(76): Guzzle\Service\Client-&gt;__call()
#12 /usr/plugins/cosUploadV5/src/Qcloud/Cos/Client.php(111): Qcloud\Cos\Client-&gt;__call()
#13 /usr/plugins/cosUploadV5/Plugin.php(178): Qcloud\Cos\Client-&gt;upload()
#14 [internal function]: TypechoPlugin\cosUploadV5\Plugin::uploadHandle()
#15 /var/Typecho/Plugin.php(446): call_user_func_array()
#16 /var/Widget/Upload.php(359): Typecho\Plugin-&gt;__call()
#17 /var/Widget/Upload.php(297): Widget\Upload::uploadHandle()
#18 /var/Widget/Upload.php(95): Widget\Upload-&gt;upload()
#19 /var/Widget/Action.php(71): Widget\Upload-&gt;action()
#20 /var/Typecho/Widget.php(155): Widget\Action-&gt;execute()
#21 /var/Typecho/Router.php(96): Typecho\Widget::widget()
#22 /index.php(23): Typecho\Router::dispatch()
#23 {main}</code></pre>
```

**Comment by dishcheng** [comment]
已更新,再试试吧

**Comment by inkss** [comment]
thx，可以使用了
